import React, { useState } from 'react';
import { BookOpen, ChevronRight, ArrowLeft, Loader } from 'lucide-react';
import { generateEducationalContent } from '../../services/geminiService';

interface EducationViewProps {
  condition: string;
}

const TOPICS = [
  { id: 'salt', title: 'Why Sodium Matters', icon: '🧂' },
  { id: 'fluids', title: 'Managing Fluid Intake', icon: '💧' },
  { id: 'movement', title: 'Safe Exercises', icon: '🚶' },
  { id: 'meds', title: 'Medication Adherence', icon: '💊' },
  { id: 'symptoms', title: 'Recognizing Warning Signs', icon: '⚠️' },
  { id: 'recipes', title: 'Easy Low-Sodium Snacks', icon: '🍏' },
];

export const EducationView: React.FC<EducationViewProps> = ({ condition }) => {
  const [selectedTopic, setSelectedTopic] = useState<string | null>(null);
  const [content, setContent] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleTopicClick = async (topic: typeof TOPICS[0]) => {
    setSelectedTopic(topic.title);
    setContent(null);
    setLoading(true);
    const result = await generateEducationalContent(topic.title, condition);
    setContent(result.content);
    setLoading(false);
  };

  if (selectedTopic) {
    return (
      <div className="p-6 h-full flex flex-col">
        <button onClick={() => { setSelectedTopic(null); setContent(null); }} className="mb-6 flex items-center text-slate-500 hover:text-indigo-600 transition-colors font-medium">
          <ArrowLeft size={20} className="mr-1" /> Back to Library
        </button>
        
        <h2 className="text-2xl font-bold text-slate-800 mb-6">{selectedTopic}</h2>
        
        {loading ? (
          <div className="flex-1 flex flex-col items-center justify-center text-slate-400">
            <div className="bg-indigo-50 p-4 rounded-full mb-4">
              <Loader size={32} className="animate-spin text-indigo-600" />
            </div>
            <p className="animate-pulse">Personalizing content for you...</p>
          </div>
        ) : (
          <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100 flex-1 overflow-y-auto">
            <div className="prose prose-slate prose-sm max-w-none">
              <div className="whitespace-pre-wrap text-slate-600 leading-relaxed">
                {content}
              </div>
            </div>
            <div className="mt-8 pt-6 border-t border-slate-100">
              <p className="text-xs text-slate-400 italic text-center">
                This content is generated by AI for educational purposes and does not replace professional medical advice.
              </p>
            </div>
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="p-6 space-y-6 h-full overflow-y-auto">
      <div className="flex items-center gap-3 mb-2">
        <div className="bg-emerald-100 p-3 rounded-full text-emerald-600">
          <BookOpen size={24} />
        </div>
        <div>
          <h2 className="text-xl font-bold text-slate-800">Heart Library</h2>
          <p className="text-xs text-slate-500">Curated guides for {condition}</p>
        </div>
      </div>

      <div className="bg-gradient-to-br from-indigo-600 to-purple-700 rounded-2xl p-5 text-white shadow-lg">
        <h3 className="font-bold text-lg mb-2">Daily Tip</h3>
        <p className="text-indigo-100 text-sm leading-relaxed">
          "Weigh yourself at the same time every morning, after using the bathroom and before breakfast, for the most accurate results."
        </p>
      </div>

      <div>
        <h3 className="font-bold text-slate-700 mb-3">Browse Topics</h3>
        <div className="grid gap-3">
          {TOPICS.map(topic => (
            <button
              key={topic.id}
              onClick={() => handleTopicClick(topic)}
              className="bg-white p-4 rounded-xl shadow-sm border border-slate-100 flex items-center justify-between group active:scale-95 transition-all hover:border-indigo-200"
            >
              <div className="flex items-center gap-4">
                <span className="text-2xl filter grayscale group-hover:grayscale-0 transition-all">{topic.icon}</span>
                <span className="font-semibold text-slate-700 group-hover:text-indigo-700 transition-colors">{topic.title}</span>
              </div>
              <ChevronRight size={20} className="text-slate-300 group-hover:text-indigo-500 transform group-hover:translate-x-1 transition-all" />
            </button>
          ))}
        </div>
      </div>
    </div>
  );
};
