import { TemplateEngine } from '../logic/TemplateEngine';
import type { NoteState } from '../logic/TemplateEngine';
import { Clipboard, Check, FileType, Printer } from 'lucide-react';
import { useState } from 'react';
import { motion } from 'framer-motion';

interface NotePreviewProps {
    state: NoteState;
}

export function NotePreview({ state }: NotePreviewProps) {
    const noteText = TemplateEngine.generate(state);
    const [copied, setCopied] = useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(noteText);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="flex flex-col h-full items-center justify-center p-8 relative z-10">

            {/* Document Paper */}
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                className="w-full max-w-3xl bg-white h-full max-h-[800px] rounded-xl shadow-2xl flex flex-col overflow-hidden border border-slate-200"
            >
                {/* Editor Toolbar */}
                <div className="px-6 py-4 border-b border-slate-100 bg-white flex justify-between items-center">
                    <div className="flex items-center gap-3">
                        <div className="bg-blue-50 p-2 rounded-lg text-blue-600">
                            <FileType className="w-5 h-5" />
                        </div>
                        <div>
                            <h3 className="font-bold text-slate-800 text-sm">Admission Note.rtf</h3>
                            <p className="text-xs text-slate-400">Auto-generated Draft</p>
                        </div>
                    </div>

                    <div className="flex items-center gap-2">
                        <button className="p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-50 rounded-lg transition-colors" title="Print">
                            <Printer className="w-4 h-4" />
                        </button>
                        <motion.button
                            whileTap={{ scale: 0.95 }}
                            onClick={handleCopy}
                            className={`flex items-center gap-2 px-4 py-2 rounded-lg font-bold text-xs transition-all shadow-lg shadow-blue-500/20 ${copied ? 'bg-emerald-500 text-white' : 'bg-blue-600 hover:bg-blue-700 text-white'}`}
                        >
                            {copied ? <Check className="w-3 h-3" /> : <Clipboard className="w-3 h-3" />}
                            {copied ? "COPIED" : "COPY TO EHR"}
                        </motion.button>
                    </div>
                </div>

                {/* Editor Body */}
                <div className="flex-1 p-8 overflow-y-auto bg-white relative">
                    {/* Line numbers (Decorative) */}
                    <div className="absolute left-4 top-8 bottom-8 w-6 border-r border-slate-100 flex flex-col items-end gap-[1.65rem] text-[10px] font-mono text-slate-300 select-none pointer-events-none pr-2">
                        {Array.from({ length: 20 }).map((_, i) => <span key={i}>{i + 1}</span>)}
                    </div>

                    <div className="pl-8 font-mono text-sm leading-loose text-slate-700 whitespace-pre-wrap selection:bg-blue-100 selection:text-blue-900">
                        {noteText}
                    </div>
                </div>

                {/* Footer */}
                <div className="px-6 py-3 border-t border-slate-100 bg-slate-50 text-[10px] text-slate-400 flex justify-between uppercase tracking-wider font-bold">
                    <span>Generated by DocuFlow Engine v1.0</span>
                    <span>{noteText.length} Characters • {noteText.split(' ').length} Words</span>
                </div>
            </motion.div>
        </div>
    );
}
